# Working with SQL

In [1]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     - -------------------------------------- 0.5/11.9 MB 1.4 MB/s eta 0:00:09
     -- ------------------------------------- 0.8/11.9 MB 1.5 MB/s eta 0:00:08
     ---- ----------------------------------- 1.3/11.9 MB 1.7 MB/s eta 0:00:07
     ----- ---------------------------------- 1.6/11.9 MB 1.8 MB/s eta 0:00:06
     ------- -------------------------------- 2.1/11.9 MB 1.8 MB/s eta 0:00:06
     ------- -------------------------------- 2.4/11.9 MB 1.9 MB/s eta 0:00:06
     -------- ------------------------------- 2.6/11.9 MB 1.7 MB/s eta 0:00:06
     -------- ------------------------------- 2.6/11.9 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 2.9/11.9 MB 1.4 MB/s eta 0:00:07
     --------- ------------------------------ 2.9/11.9 MB 1.4 MB/s eta 0:00:07
     ---------- ----------------------------- 3.1/11.9 MB 1.4 MB/s eta 0:00:07
     ------------ --------------------------- 3.7/11.9 MB 1.4 MB/s eta 0:00:06
     -------------- ------------------------- 4.2/11.9 MB 1.5 MB/s eta 0:00:06
     ---------------- ----------------------- 5.0/11.9 MB 1.6 MB/s eta 0:00:05
     ----------------- ---------------------- 5.2/11.9 MB 1.7 MB/s eta 0:00:04
     ------------------- -------------------- 5.8/11.9 MB 1.7 MB/s eta 0:00:04
     --------------------- ------------------ 6.3/11.9 MB 1.7 MB/s eta 0:00:04
     ---------------------- ----------------- 6.6/11.9 MB 1.7 MB/s eta 0:00:04
     ----------------------- ---------------- 7.1/11.9 MB 1.7 MB/s eta 0:00:03
     ------------------------- -------------- 7.6/11.9 MB 1.8 MB/s eta 0:00:03
     -------------------------- ------------- 7.9/11.9 MB 1.7 MB/s eta 0:00:03
     ---------------------------- ----------- 8.4/11.9 MB 1.8 MB/s eta 0:00:02
     ------------------------------ --------- 9.2/11.9 MB 1.8 MB/s eta 0:00:02
     --------------------------------- ------ 10.0/11.9 MB 1.9 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 2.0 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 2.1 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 2.1 MB/s  0:00:05
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248051 sha256=398a196365a17df99cfabf8fe4c1721b91fbe3dc0bc779f844191393de8636a5
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [2]:
import mysql.connector

In [8]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [6]:
import pandas as pd

In [9]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

C:\Users\DELL\AppData\Local\Temp\ipykernel_22496\4272969784.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

In [11]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CountryCode  984 non-null    object
 1   Language     984 non-null    object
 2   IsOfficial   984 non-null    object
 3   Percentage   984 non-null    float64
dtypes: float64(1), object(3)
memory usage: 30.9+ KB

In [17]:
df = pd.read_sql_query("SELECT * FROM country",conn)

C:\Users\DELL\AppData\Local\Temp\ipykernel_22496\4111570038.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM country",conn)

In [18]:
df

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW